### ISSUE TITLE
crypto.verifySignature is broken for signatures with expiration

### ISSUE THREAD

**Issue by DmitriyMV** [ProtonMail/gopenpgp#231]
`verifySignature` is broken if it tries to retry with the actual verification time. It doesn't reset `origText` reader, so it has nothing to read on second attempt.

Relevant [parts](https://github.com/ProtonMail/gopenpgp/blob/main/crypto/signature.go#L245-L262).

**Comment by marinthiercelin** [comment]
Hey, thanks for opening the issue.
That seems indeed to be broken.
I'm a bit confused why you would revert your project to v2.5.2 though, the issue seems older than this version.
Do you have any example data that I could use to trigger the bug ?

**Comment by DmitriyMV** [comment]
> I'm a bit confused why you would revert your project to v2.5.2 though, the issue seems older than this version.

`verifySignature` is indeed broken in 2.5.2 (it doesn't return an error if signature expired) but we are not hitting it, because we have check called [IsExpired](https://github.com/siderolabs/go-api-signature/blob/69886dcc1343561add3b4b86ef160e0a1876d97f/pkg/pgp/key.go#L98-L119) which is doing what it must. So that's a reason for revert. 

> Do you have any example data that I could use to trigger the bug ?

[Sure, here it is.](https://go.dev/play/p/yaPW-ShcZUr)

**Comment by marinthiercelin** [comment]
Hey, It's indeed tricky to fix while keeping the API.

I think, as a short term fix, we should go with a variant of your second approach.
If `origText` supports `Seek` use it and verify again.
But if it does not support Seek, I don't think we should read it all in a buffer, that could be quite bad for memory usage.
Instead I think we should just not reattempt the verification.
That means that if you verify with `VerifyDetachedStream` with a non seekable stream, the verification might fail.
So it's only a partial fix.

For a complete fix, I think we should instead rethink how we do the verification, and manually check the dates for expiration, rather than reattempting verification with a different time.

If you want to open a PR for either the partial fix, or look into the complete fix, it would be greatly appreciated.

**Comment by DmitriyMV** [comment]
Opened an PR for partial fix.

**Comment by marinthiercelin** [comment]
Thanks a lot for your submission @DmitriyMV

**Comment by smira** [comment]
@DmitriyMV is there something else which needs to fixed here? as it seems that the verification is still broken?

**Comment by DmitriyMV** [comment]
@smira It's a partial fix in a sense that it only supports messages which have `Seek` method. It may still trigger for non Seek-able streams, but for the most part it is good enough.
