### ISSUE TITLE
please add helper.EncryptMessageArmoredFromByte or default use []byte mode

### ISSUE THREAD

**Issue by JokerCatz** [ProtonMail/gopenpgp#53]
Hi , I got a funny bug , about `string` and `[]byte` in `helper`

if I read a binary image data and `[]byte` convert to `string` and use `helper.EncryptMessageArmored` + `helper.DecryptMessageArmored` to encode / decode it , it will be success & source / result checksum verify will be same

but if I use command line `gpg` (v1.4 , v2.x) to decode it , the binary will lost like `\x00\x00\x00\x0d\x00\x00\x00\x0d` (`\r` char) and checksum match will be fail

I tried if I don't use `helper.EncryptMessageArmored` and use it source code , change to use `crypto.NewPlainMessage(rawSourceBytes)` , and use `gpg` command to decode it , source / result checksum verify will  success

so I just suggest add a `helper.EncryptMessageArmoredFromByte` function or use default use `[]byte` , this condition will be okay

and it no matter about `gpg` encode and golang decode condition

**Comment by wussler** [comment]
Hi @JokerCatz, 
this is intended behaviour due to the text/byte flag in the OpenPGP standard.

Helpers are only meant for basic encryption/decryption functions and it would not suitable to create them for all the possible functions.
I'd suggest to have a look [here](https://github.com/ProtonMail/gopenpgp#encrypt--decrypt-with-pgp-keys) the example "With binary data or advanced modes", and in case you reuse this code a lot just have a wrapper around it :)

Cheers,
Aron
